import type { ShoppingList, ShoppingListItem } from '@/types/domain';

export type GroceryService = 'instacart' | 'amazonFresh' | 'walmart' | 'csv' | 'text';

export interface ExportConfig {
  name: string;
  icon: string;
  color: string;
}

export const GROCERY_SERVICES: Record<GroceryService, ExportConfig> = {
  instacart: {
    name: 'Instacart',
    icon: '🛒',
    color: 'hsl(112, 60%, 43%)',
  },
  amazonFresh: {
    name: 'Amazon Fresh',
    icon: '📦',
    color: 'hsl(35, 100%, 50%)',
  },
  walmart: {
    name: 'Walmart',
    icon: '⭐',
    color: 'hsl(205, 100%, 35%)',
  },
  csv: {
    name: 'CSV File',
    icon: '📊',
    color: 'hsl(150, 60%, 45%)',
  },
  text: {
    name: 'Plain Text',
    icon: '📝',
    color: 'hsl(220, 15%, 50%)',
  },
};

function formatQuantity(item: ShoppingListItem): string {
  if (item.unit === 'pieces') {
    return `${item.total_quantity} pieces`;
  }
  
  if (item.total_quantity >= 1000) {
    const kg = item.total_quantity / 1000;
    return item.unit === 'g' ? `${kg.toFixed(2)} kg` : `${kg.toFixed(2)} L`;
  }
  
  return `${item.total_quantity}${item.unit}`;
}

export function exportToInstacart(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `${item.display_name} - ${formatQuantity(item)}`)
    .join('\n');
  
  const content = `Gurmaio Shopping List - ${new Date().toLocaleDateString()}

${items}

Total Items: ${shoppingList.summary.total_items}
Estimated Cost: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Copy these items into your Instacart cart or search for each item in the app.`;
  
  copyToClipboard(content, 'Instacart list copied! Paste it into your Instacart app.');
}

export function exportToAmazonFresh(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `• ${item.display_name} (${formatQuantity(item)})`)
    .join('\n');
  
  const content = `Amazon Fresh Shopping List
Generated by Gurmaio on ${new Date().toLocaleDateString()}

${items}

Total: ${shoppingList.summary.total_items} items | Est. €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Search for each item in Amazon Fresh or Whole Foods.`;
  
  copyToClipboard(content, 'Amazon Fresh list copied! Paste it into your Amazon app.');
}

export function exportToWalmart(shoppingList: ShoppingList): void {
  const items = shoppingList.items
    .map(item => `${item.display_name} (${formatQuantity(item)})`)
    .join('\n');
  
  const content = `Walmart Grocery List - Gurmaio
${new Date().toLocaleDateString()}

Shopping List:
${items}

Summary:
- ${shoppingList.summary.total_items} items
- Estimated total: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}

Use Walmart Grocery app or website to add these items to your cart.`;
  
  copyToClipboard(content, 'Walmart list copied! Paste it into your Walmart Grocery app.');
}

export function exportToCSV(shoppingList: ShoppingList): void {
  const headers = 'Item Name,Quantity,Unit,Estimated Price (EUR)';
  
  const rows = shoppingList.items.map(item => 
    `"${item.display_name}",${item.total_quantity},${item.unit},${item.estimated_price_eur.toFixed(2)}`
  );
  
  const csv = [headers, ...rows].join('\n');
  
  downloadFile(csv, `gurmaio-shopping-list-${Date.now()}.csv`, 'text/csv');
}

export function exportToText(shoppingList: ShoppingList): void {
  const content = `GURMAIO SHOPPING LIST
Generated: ${new Date().toLocaleString()}
Plan ID: ${shoppingList.plan_id}

${'='.repeat(50)}

${shoppingList.items.map((item, index) => 
  `${(index + 1).toString().padStart(2, '0')}. ${item.display_name}
    Quantity: ${formatQuantity(item)}
    Est. Price: €${item.estimated_price_eur.toFixed(2)}`
).join('\n\n')}

${'='.repeat(50)}

SUMMARY
-------
Total Items: ${shoppingList.summary.total_items}
Plan Cost: €${shoppingList.summary.plan_cost_eur.toFixed(2)}
Shopping Cost: €${shoppingList.summary.total_shopping_cost_eur.toFixed(2)}
Waste/Extra: €${shoppingList.summary.waste_cost_eur.toFixed(2)}

${'='.repeat(50)}

Note: Prices are estimates based on regional averages.
Actual costs may vary by store and location.`;
  
  downloadFile(content, `gurmaio-shopping-list-${Date.now()}.txt`, 'text/plain');
}

function copyToClipboard(text: string, successMessage: string): void {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text)
      .then(() => {
        if (typeof window !== 'undefined' && 'toast' in window) {
          (window as any).showToast?.(successMessage);
        }
      })
      .catch((err) => {
        console.error('Failed to copy to clipboard:', err);
        fallbackCopy(text);
      });
  } else {
    fallbackCopy(text);
  }
}

function fallbackCopy(text: string): void {
  const textArea = document.createElement('textarea');
  textArea.value = text;
  textArea.style.position = 'fixed';
  textArea.style.left = '-999999px';
  textArea.style.top = '-999999px';
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  
  try {
    document.execCommand('copy');
    if (typeof window !== 'undefined' && 'toast' in window) {
      (window as any).showToast?.('Copied to clipboard!');
    }
  } catch (err) {
    console.error('Fallback copy failed:', err);
  }
  
  document.body.removeChild(textArea);
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
  
  if (typeof window !== 'undefined' && 'toast' in window) {
    (window as any).showToast?.(`Downloaded ${filename}`);
  }
}

export function exportShoppingList(shoppingList: ShoppingList, service: GroceryService): void {
  switch (service) {
    case 'instacart':
      exportToInstacart(shoppingList);
      break;
    case 'amazonFresh':
      exportToAmazonFresh(shoppingList);
      break;
    case 'walmart':
      exportToWalmart(shoppingList);
      break;
    case 'csv':
      exportToCSV(shoppingList);
      break;
    case 'text':
      exportToText(shoppingList);
      break;
  }
}
